apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base 디렉토리에 있는 모든 애플리케이션(컴포넌트)들을 포함시킵니다.
resources:
  #- ../../base/metallb
  - ../../base/elasticsearch
  #- ../../base/kibana
  #- ../../base/elastalert
  #- ../../base/es-archiver
  #- ../../base/kafka-connector
  #- ../../base/secrets

# --- 예시: 만약 production 환경에서만 특정 설정을 변경하고 싶다면 ---
# 예를 들어, elastalert의 복제본 수를 3개로 늘리고 싶을 때
# patchesStrategicMerge:
#   - |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: elastalert
#     spec:
#       replicas: 3