apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-elastic-password.yaml
  - sealed-aws-credentials.yaml
  - sealed-webhook-url-secret.yaml
  - sealed-dockerhub-secret.yaml
  - sealed-kibana-encryption-key-secret.yaml
  - sealed-kafka-broker-ca-secret.yaml